# generated by datamodel-codegen:
#   filename:  schema.deref.yaml
#   timestamp: 2025-09-29T14:22:11+00:00

from __future__ import annotations
from enum import Enum
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class Version(Enum):
    v1 = "v1"


class Prompt(BaseModel):
    role: Optional[str] = Field(
        None, description='Prompt role (e.g., "system", "user", "assistant")'
    )
    content: str = Field(..., description='Prompt content (e.g., "You are a helpful assistant.")')


class Type(Enum):
    ChromaStore = "ChromaStore"
    QdrantStore = "QdrantStore"


class Type1(Enum):
    HuggingFaceEmbedder = "HuggingFaceEmbedder"
    OllamaEmbedder = "OllamaEmbedder"
    OpenAIEmbedder = "OpenAIEmbedder"
    SentenceTransformerEmbedder = "SentenceTransformerEmbedder"


class EmbeddingStrategy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="Strategy identifier")
    type: Type1 = Field(..., description="Embedding type")
    config: Optional[dict[str, Any]] = Field(None, description="Embedder configuration")
    condition: Optional[str] = Field(
        None,
        description="Optional condition for when to use this embedding (e.g., doc.type == 'code')",
    )
    priority: Optional[int] = Field(0, description="Priority for automatic selection")


class Type2(Enum):
    VectorRetriever = "VectorRetriever"
    HybridRetriever = "HybridRetriever"
    BM25Retriever = "BM25Retriever"
    RerankedRetriever = "RerankedRetriever"
    GraphRetriever = "GraphRetriever"
    ElasticRetriever = "ElasticRetriever"
    BasicSimilarityStrategy = "BasicSimilarityStrategy"
    MetadataFilteredStrategy = "MetadataFilteredStrategy"
    MultiQueryStrategy = "MultiQueryStrategy"
    RerankedStrategy = "RerankedStrategy"
    HybridUniversalStrategy = "HybridUniversalStrategy"


class RetrievalStrategy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="Strategy identifier")
    type: Type2 = Field(..., description="Retrieval type")
    config: Optional[dict[str, Any]] = Field(None, description="Retrieval configuration")
    default: Optional[bool] = Field(False, description="Whether this is the default strategy")


class Database(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]*$", min_length=1, max_length=50) = Field(
        ..., description="Unique database identifier"
    )
    type: Type = Field(
        ..., description="Database type (accepts both short names and Store class names)"
    )
    config: Optional[dict[str, Any]] = Field(None, description="Database-specific configuration")
    embedding_strategies: Optional[list[EmbeddingStrategy]] = Field(
        None,
        description="Multiple embedding strategies for hybrid search",
        title="Embedding Strategies",
    )
    retrieval_strategies: Optional[list[RetrievalStrategy]] = Field(
        None,
        description="Multiple retrieval strategies for different query patterns",
        title="Retrieval Strategies",
    )
    default_embedding_strategy: Optional[str] = Field(
        None, description="Name of the default embedding strategy to use"
    )
    default_retrieval_strategy: Optional[str] = Field(
        None, description="Name of the default retrieval strategy to use"
    )


class Type3(Enum):
    CSVParser_LlamaIndex = "CSVParser_LlamaIndex"
    CSVParser_Pandas = "CSVParser_Pandas"
    CSVParser_Python = "CSVParser_Python"
    DirectoryParser = "DirectoryParser"
    DocxParser_LlamaIndex = "DocxParser_LlamaIndex"
    DocxParser_PythonDocx = "DocxParser_PythonDocx"
    ExcelParser_LlamaIndex = "ExcelParser_LlamaIndex"
    ExcelParser_OpenPyXL = "ExcelParser_OpenPyXL"
    ExcelParser_Pandas = "ExcelParser_Pandas"
    MarkdownParser_LlamaIndex = "MarkdownParser_LlamaIndex"
    MarkdownParser_Python = "MarkdownParser_Python"
    PDFParser_LlamaIndex = "PDFParser_LlamaIndex"
    PDFParser_PyPDF2 = "PDFParser_PyPDF2"
    TextParser_LlamaIndex = "TextParser_LlamaIndex"
    TextParser_Python = "TextParser_Python"


class Parser(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Optional[Type3] = Field(None, description="Parser type")
    config: Optional[dict[str, Any]] = Field(None, description="Parser configuration")
    file_extensions: Optional[list[constr(pattern=r"^\.[a-zA-Z0-9]+$")]] = Field(
        None,
        description='File extensions this parser handles (e.g., [".pdf", ".PDF"])',
        examples=[[".pdf", ".PDF"], [".csv", ".tsv"], [".md", ".markdown"]],
    )
    file_include_patterns: Optional[list[str]] = Field(
        None,
        description='Glob patterns for files to include (e.g., ["*.pdf", "report_*.pdf"])',
        examples=[["*.pdf", "*.PDF"], ["report_*.csv"], ["README*", "*.md"]],
    )
    file_exclude_patterns: Optional[list[str]] = Field(
        None,
        description='Glob patterns for files to exclude (e.g., ["*_draft.pdf", "*.tmp"])',
        examples=[["*_draft.pdf", "*.tmp.pdf"], ["~$*", "*.bak"]],
    )
    priority: Optional[int] = Field(0, description="Priority for automatic selection")
    mime_types: Optional[list[str]] = Field(
        None,
        description='MIME types this parser handles (e.g., ["application/pdf"])',
        examples=[
            ["application/pdf"],
            ["text/csv", "text/tab-separated-values"],
            ["text/markdown", "text/x-markdown"],
        ],
    )
    fallback_parser: Optional[str] = Field(None, description="Parser to use if this one fails")


class Extractor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str = Field(..., description="Extractor type")
    config: Optional[dict[str, Any]] = Field(None, description="Extractor configuration")
    required_for: Optional[list[str]] = Field(
        None, description="Database names that require this extractor"
    )
    condition: Optional[str] = Field(
        None, description="Optional condition for when to use this extractor"
    )
    file_include_patterns: Optional[list[str]] = Field(
        None,
        description="Glob patterns for files to apply this extractor to",
        examples=[["*.pdf", "*.PDF"], ["*"]],
    )
    file_exclude_patterns: Optional[list[str]] = Field(
        None,
        description="Glob patterns for files to exclude from this extractor",
        examples=[["*.tmp", "*.bak"]],
    )
    priority: Optional[conint(ge=0, le=1000)] = Field(
        50, description="Extractor priority (higher = apply first)"
    )


class DataProcessingStrategy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]*$", min_length=1, max_length=50) = Field(
        ..., description="Unique strategy identifier"
    )
    description: Optional[constr(min_length=10, max_length=500)] = Field(
        None, description="Strategy description"
    )
    parsers: list[Parser] = Field(
        ..., description="Document parsers in processing order", min_length=1, title="Parsers"
    )
    extractors: Optional[list[Extractor]] = Field(
        None, description="Metadata and feature extractors", title="Extractors"
    )


class Rag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    databases: Optional[list[Database]] = Field(
        None,
        description="Independent database definitions with their own embedding/retrieval strategies",
        min_length=1,
        title="Database Configurations",
    )
    data_processing_strategies: Optional[list[DataProcessingStrategy]] = Field(
        None,
        description="Processing pipelines for parsers and extractors",
        min_length=1,
        title="Data Processing Strategies",
    )


class Dataset(BaseModel):
    name: str = Field(..., description="Dataset name")
    data_processing_strategy: str = Field(
        ..., description="RAG data processing strategy to use for the dataset"
    )
    database: str = Field(..., description="RAG database to use for the dataset")
    files: list[str] = Field(..., description="List of file hashes")


class Provider(Enum):
    openai = "openai"
    ollama = "ollama"


class AgentHandler(Enum):
    simple_chat = "simple_chat"
    simple_rag = "simple_rag"
    structured_rag = "structured_rag"
    classifier = "classifier"


class Runtime(BaseModel):
    provider: Provider
    model: str = Field(..., description="Model name or ID")
    base_url: Optional[str] = Field(None, description="Base URL for the provider")
    api_key: Optional[str] = Field(
        None, description="API key for the provider (optional, not required for Ollama)"
    )
    instructor_mode: Optional[str] = Field(
        None,
        description="Instructor mode to use for structured output (e.g., tools, json, md_json, anthropic_tools, gemini_json, etc.)",
    )
    agent_handler: Optional[AgentHandler] = Field(
        "structured_rag",
        description="Selects the orchestration pipeline for this runtime (e.g., simple_chat, simple_rag, structured_rag, classifier)",
    )
    model_api_parameters: Optional[Any] = Field(
        None, description="Additional parameters passed to the API provider"
    )


class Model(BaseModel):
    alias: str = Field(
        ..., description='Unique identifier (e.g., "fast", "creative") used to select this model.'
    )
    display_name: Optional[str] = Field(None, description="Human-friendly name for UIs.")
    description: Optional[str] = Field(
        None, description="Additional details about when to use this model."
    )
    provider: Provider
    model: str = Field(..., description="Provider-specific model name or ID.")
    base_url: Optional[str] = Field(
        None, description="Base URL for provider requests (e.g., custom Ollama host)."
    )
    api_key: Optional[str] = Field(
        None, description="API key (optional, not required for local providers)."
    )
    instructor_mode: Optional[str] = Field(
        None, description="Preferred instructor mode when structured output is supported."
    )
    agent_handler: Optional[AgentHandler] = Field(
        "structured_rag", description="Chat orchestration pipeline associated with this model."
    )
    default: Optional[bool] = Field(
        False, description="Marks this entry as the default model when none is specified."
    )
    model_api_parameters: Optional[dict[str, Any]] = Field(
        None, description="Additional parameters passed to the provider when creating completions."
    )


class LlamaFarmConfig1(BaseModel):
    version: Version = Field(..., description='Config version, must be "v1"')
    name: str = Field(..., description="Project name", examples=["my-project"])
    namespace: str = Field(..., description="Project namespace", examples=["my-namespace"])
    prompts: Optional[list[Prompt]] = []
    rag: Optional[Rag] = Field(
        None,
        description="Schema for RAG system strategy configurations",
        title="RAG Strategy Configuration Schema",
    )
    datasets: Optional[list[Dataset]] = Field([], description="List of dataset configurations")
    runtime: Runtime
    models: Optional[list[Model]] = Field(None, title="LlamaFarm Model Definitions")


class Type4(Enum):
    ChromaStore = "ChromaStore"
    QdrantStore = "QdrantStore"


class Type5(Enum):
    HuggingFaceEmbedder = "HuggingFaceEmbedder"
    OllamaEmbedder = "OllamaEmbedder"
    OpenAIEmbedder = "OpenAIEmbedder"
    SentenceTransformerEmbedder = "SentenceTransformerEmbedder"


class EmbeddingStrategy1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="Strategy identifier")
    type: Type5 = Field(..., description="Embedding type")
    config: Optional[dict[str, Any]] = Field(None, description="Embedder configuration")
    condition: Optional[str] = Field(
        None,
        description="Optional condition for when to use this embedding (e.g., doc.type == 'code')",
    )
    priority: Optional[int] = Field(0, description="Priority for automatic selection")


class Type6(Enum):
    VectorRetriever = "VectorRetriever"
    HybridRetriever = "HybridRetriever"
    BM25Retriever = "BM25Retriever"
    RerankedRetriever = "RerankedRetriever"
    GraphRetriever = "GraphRetriever"
    ElasticRetriever = "ElasticRetriever"
    BasicSimilarityStrategy = "BasicSimilarityStrategy"
    MetadataFilteredStrategy = "MetadataFilteredStrategy"
    MultiQueryStrategy = "MultiQueryStrategy"
    RerankedStrategy = "RerankedStrategy"
    HybridUniversalStrategy = "HybridUniversalStrategy"


class RetrievalStrategy1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="Strategy identifier")
    type: Type6 = Field(..., description="Retrieval type")
    config: Optional[dict[str, Any]] = Field(None, description="Retrieval configuration")
    default: Optional[bool] = Field(False, description="Whether this is the default strategy")


class Database1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]*$", min_length=1, max_length=50) = Field(
        ..., description="Unique database identifier"
    )
    type: Type4 = Field(
        ..., description="Database type (accepts both short names and Store class names)"
    )
    config: Optional[dict[str, Any]] = Field(None, description="Database-specific configuration")
    embedding_strategies: Optional[list[EmbeddingStrategy1]] = Field(
        None,
        description="Multiple embedding strategies for hybrid search",
        title="Embedding Strategies",
    )
    retrieval_strategies: Optional[list[RetrievalStrategy1]] = Field(
        None,
        description="Multiple retrieval strategies for different query patterns",
        title="Retrieval Strategies",
    )
    default_embedding_strategy: Optional[str] = Field(
        None, description="Name of the default embedding strategy to use"
    )
    default_retrieval_strategy: Optional[str] = Field(
        None, description="Name of the default retrieval strategy to use"
    )


class Type7(Enum):
    CSVParser_LlamaIndex = "CSVParser_LlamaIndex"
    CSVParser_Pandas = "CSVParser_Pandas"
    CSVParser_Python = "CSVParser_Python"
    DirectoryParser = "DirectoryParser"
    DocxParser_LlamaIndex = "DocxParser_LlamaIndex"
    DocxParser_PythonDocx = "DocxParser_PythonDocx"
    ExcelParser_LlamaIndex = "ExcelParser_LlamaIndex"
    ExcelParser_OpenPyXL = "ExcelParser_OpenPyXL"
    ExcelParser_Pandas = "ExcelParser_Pandas"
    MarkdownParser_LlamaIndex = "MarkdownParser_LlamaIndex"
    MarkdownParser_Python = "MarkdownParser_Python"
    PDFParser_LlamaIndex = "PDFParser_LlamaIndex"
    PDFParser_PyPDF2 = "PDFParser_PyPDF2"
    TextParser_LlamaIndex = "TextParser_LlamaIndex"
    TextParser_Python = "TextParser_Python"


class Parser1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Optional[Type7] = Field(None, description="Parser type")
    config: Optional[dict[str, Any]] = Field(None, description="Parser configuration")
    file_extensions: Optional[list[constr(pattern=r"^\.[a-zA-Z0-9]+$")]] = Field(
        None,
        description='File extensions this parser handles (e.g., [".pdf", ".PDF"])',
        examples=[[".pdf", ".PDF"], [".csv", ".tsv"], [".md", ".markdown"]],
    )
    file_include_patterns: Optional[list[str]] = Field(
        None,
        description='Glob patterns for files to include (e.g., ["*.pdf", "report_*.pdf"])',
        examples=[["*.pdf", "*.PDF"], ["report_*.csv"], ["README*", "*.md"]],
    )
    file_exclude_patterns: Optional[list[str]] = Field(
        None,
        description='Glob patterns for files to exclude (e.g., ["*_draft.pdf", "*.tmp"])',
        examples=[["*_draft.pdf", "*.tmp.pdf"], ["~$*", "*.bak"]],
    )
    priority: Optional[int] = Field(0, description="Priority for automatic selection")
    mime_types: Optional[list[str]] = Field(
        None,
        description='MIME types this parser handles (e.g., ["application/pdf"])',
        examples=[
            ["application/pdf"],
            ["text/csv", "text/tab-separated-values"],
            ["text/markdown", "text/x-markdown"],
        ],
    )
    fallback_parser: Optional[str] = Field(None, description="Parser to use if this one fails")


class DataProcessingStrategy1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]*$", min_length=1, max_length=50) = Field(
        ..., description="Unique strategy identifier"
    )
    description: Optional[constr(min_length=10, max_length=500)] = Field(
        None, description="Strategy description"
    )
    parsers: list[Parser1] = Field(
        ..., description="Document parsers in processing order", min_length=1, title="Parsers"
    )
    extractors: Optional[list[Extractor]] = Field(
        None, description="Metadata and feature extractors", title="Extractors"
    )


class Rag1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    databases: Optional[list[Database1]] = Field(
        None,
        description="Independent database definitions with their own embedding/retrieval strategies",
        min_length=1,
        title="Database Configurations",
    )
    data_processing_strategies: Optional[list[DataProcessingStrategy1]] = Field(
        None,
        description="Processing pipelines for parsers and extractors",
        min_length=1,
        title="Data Processing Strategies",
    )


class Runtime1(BaseModel):
    provider: Provider
    model: str = Field(..., description="Model name or ID")
    base_url: Optional[str] = Field(None, description="Base URL for the provider")
    api_key: Optional[str] = Field(
        None, description="API key for the provider (optional, not required for Ollama)"
    )
    instructor_mode: Optional[str] = Field(
        None,
        description="Instructor mode to use for structured output (e.g., tools, json, md_json, anthropic_tools, gemini_json, etc.)",
    )
    agent_handler: Optional[AgentHandler] = Field(
        "structured_rag",
        description="Selects the orchestration pipeline for this runtime (e.g., simple_chat, simple_rag, structured_rag, classifier)",
    )
    model_api_parameters: Optional[Any] = Field(
        None, description="Additional parameters passed to the API provider"
    )


class Model1(BaseModel):
    alias: str = Field(
        ..., description='Unique identifier (e.g., "fast", "creative") used to select this model.'
    )
    display_name: Optional[str] = Field(None, description="Human-friendly name for UIs.")
    description: Optional[str] = Field(
        None, description="Additional details about when to use this model."
    )
    provider: Provider
    model: str = Field(..., description="Provider-specific model name or ID.")
    base_url: Optional[str] = Field(
        None, description="Base URL for provider requests (e.g., custom Ollama host)."
    )
    api_key: Optional[str] = Field(
        None, description="API key (optional, not required for local providers)."
    )
    instructor_mode: Optional[str] = Field(
        None, description="Preferred instructor mode when structured output is supported."
    )
    agent_handler: Optional[AgentHandler] = Field(
        "structured_rag", description="Chat orchestration pipeline associated with this model."
    )
    default: Optional[bool] = Field(
        False, description="Marks this entry as the default model when none is specified."
    )
    model_api_parameters: Optional[dict[str, Any]] = Field(
        None, description="Additional parameters passed to the provider when creating completions."
    )


class ResolvedModel(BaseModel):
    alias: str
    display_name: Optional[str] = None
    description: Optional[str] = None
    provider: Provider
    model: str
    base_url: Optional[str] = None
    api_key: Optional[str] = None
    instructor_mode: Optional[str] = None
    agent_handler: AgentHandler = AgentHandler.structured_rag
    model_api_parameters: Optional[Dict[str, Any]] = None
    default: bool = False
    model_api_parameters: Optional[dict[str, Any]] = Field(
        None, description="Additional parameters passed to the provider when creating completions."
    )


class LlamaFarmConfig2(BaseModel):
    version: Version = Field(..., description='Config version, must be "v1"')
    name: str = Field(..., description="Project name", examples=["my-project"])
    namespace: str = Field(..., description="Project namespace", examples=["my-namespace"])
    prompts: Optional[list[Prompt]] = []
    rag: Optional[Rag1] = Field(
        None,
        description="Schema for RAG system strategy configurations",
        title="RAG Strategy Configuration Schema",
    )
    datasets: Optional[list[Dataset]] = Field([], description="List of dataset configurations")
    runtime: Optional[Runtime1] = None
    models: list[Model1] = Field(..., title="LlamaFarm Model Definitions")


class LlamaFarmConfig(RootModel[Union[LlamaFarmConfig1, LlamaFarmConfig2]]):
    root: Union[LlamaFarmConfig1, LlamaFarmConfig2] = Field(..., title="LlamaFarm Config")

    def resolved_models(self) -> List[ResolvedModel]:
        cfg = self.root
        models: List[ResolvedModel] = []
        used_aliases: set[str] = set()

        def append_model(resolved: ResolvedModel) -> None:
            if resolved.alias in used_aliases:
                raise ValueError(f"Duplicate model alias '{resolved.alias}' in configuration")
            used_aliases.add(resolved.alias)
            models.append(resolved)

        if isinstance(cfg, LlamaFarmConfig2):
            for model in cfg.models:
                append_model(_resolved_from_model(model.alias, model.display_name, model.description, model.provider, model.model, model.base_url, model.api_key, model.instructor_mode, model.agent_handler, model.model_api_parameters, bool(model.default)))
            if cfg.runtime is not None:
                alias = "default" if not models else "runtime"
                runtime_model = _resolved_from_runtime(alias, cfg.runtime)
                if not models and not any(model.default for model in models):
                    runtime_model.default = True
                append_model(runtime_model)
        else:
            if cfg.models:
                for model in cfg.models:
                    append_model(_resolved_from_model(model.alias, model.display_name, model.description, model.provider, model.model, model.base_url, model.api_key, model.instructor_mode, model.agent_handler, model.model_api_parameters, bool(model.default)))
            alias = "default" if not models else "runtime"
            runtime_model = _resolved_from_runtime(alias, cfg.runtime)
            if not models and not any(model.default for model in models):
                runtime_model.default = True
            append_model(runtime_model)

        if models and not any(model.default for model in models):
            models[0].default = True
        return models

    def default_model(self) -> ResolvedModel:
        models = self.resolved_models()
        if not models:
            raise ValueError("No models configured")
        for model in models:
            if model.default:
                return model
        return models[0]

    def resolve_model(self, alias: Optional[str]) -> ResolvedModel:
        models = self.resolved_models()
        if not models:
            raise ValueError("No models configured")
        if alias:
            for model in models:
                if model.alias == alias or model.model == alias:
                    return model
            raise ValueError(f"Unknown model alias '{alias}'")
        return self.default_model()


def _resolved_from_model(
    alias: str,
    display_name: Optional[str],
    description: Optional[str],
    provider: Provider,
    model: str,
    base_url: Optional[str],
    api_key: Optional[str],
    instructor_mode: Optional[str],
    agent_handler: Optional[AgentHandler],
    params: Optional[Dict[str, Any]],
    default: bool,
) -> ResolvedModel:
    return ResolvedModel(
        alias=alias,
        display_name=display_name,
        description=description,
        provider=provider,
        model=model,
        base_url=base_url,
        api_key=api_key,
        instructor_mode=instructor_mode,
        agent_handler=agent_handler or AgentHandler.structured_rag,
        model_api_parameters=_coerce_params(params),
        default=default,
    )


def _resolved_from_runtime(alias: str, runtime: Union[Runtime, Runtime1]) -> ResolvedModel:
    return ResolvedModel(
        alias=alias,
        provider=runtime.provider,
        model=runtime.model,
        base_url=runtime.base_url,
        api_key=runtime.api_key,
        instructor_mode=runtime.instructor_mode,
        agent_handler=runtime.agent_handler or AgentHandler.structured_rag,
        model_api_parameters=_coerce_params(runtime.model_api_parameters),
        default=False,
    )


def _coerce_params(params: Optional[Any]) -> Optional[Dict[str, Any]]:
    if params is None:
        return None
    if isinstance(params, dict):
        return params
    try:
        return dict(params)
    except Exception:
        return None
