# generated by datamodel-codegen:
#   filename:  api_schema.yaml
#   timestamp: 2025-10-08T23:00:14+00:00

from __future__ import annotations
from pydantic import BaseModel, Field
from typing import Any, Optional
from enum import Enum


class AgentRunRequest(BaseModel):
    namespace: str = Field(..., description="Project namespace")
    project: str = Field(..., description="Project name")
    agent_config: dict[str, Any] = Field(..., description="Agent configuration from llamafarm.yaml")
    project_config: dict[str, Any] = Field(..., description="Full project configuration")
    input_data: Any = Field(..., description="Input data for agent execution (any type)")
    stream: Optional[bool] = Field(False, description="Enable streaming response")


class Status(Enum):
    completed = "completed"
    failed = "failed"


class AgentRunResponse(BaseModel):
    agent_name: str = Field(..., description="Name of the agent that was executed")
    status: Status = Field(..., description="Execution status")
    result: Optional[Any] = Field(
        None, description="Agent execution result (optional, null if failed)"
    )
    error: Optional[str] = Field(None, description="Error message if execution failed (optional)")


class AgentTypeInfo(BaseModel):
    type: str = Field(..., description="Agent type identifier")
    class_: Optional[str] = Field(None, alias="class", description="Python class name")
    module: Optional[str] = Field(None, description="Python module path")
    has_factory: Optional[bool] = Field(False, description="Whether agent has a factory function")


class ListAgentTypesResponse(BaseModel):
    total: int = Field(..., description="Total number of agent types")
    types: list[AgentTypeInfo] = Field(..., description="List of agent type information")


class Status1(Enum):
    healthy = "healthy"
    unhealthy = "unhealthy"


class HealthCheckResponse(BaseModel):
    status: Status1 = Field(..., description="Service health status")
    service: str = Field(..., description="Service name")
    version: Optional[str] = Field(None, description="Service version")
    agent_types_loaded: Optional[int] = Field(None, description="Number of agent types loaded")
    agent_types: Optional[list[str]] = Field(None, description="List of loaded agent types")
    server_url: Optional[str] = Field(None, description="Configured server URL")


class Status2(Enum):
    ready = "ready"
    not_ready = "not_ready"


class ReadinessCheckResponse(BaseModel):
    status: Status2 = Field(..., description="Service readiness status")
    agent_types: Optional[int] = Field(None, description="Number of agent types loaded")
    reason: Optional[str] = Field(None, description="Reason for not ready status (optional)")


class Model(BaseModel):
    agentRunRequest: Optional[AgentRunRequest] = None
    agentRunResponse: Optional[AgentRunResponse] = None
    agentTypeInfo: Optional[AgentTypeInfo] = None
    listAgentTypesResponse: Optional[ListAgentTypesResponse] = None
    healthCheckResponse: Optional[HealthCheckResponse] = None
    readinessCheckResponse: Optional[ReadinessCheckResponse] = None
