# generated by datamodel-codegen:
#   filename:  schema.yaml
#   timestamp: 2025-10-08T23:00:13+00:00

from __future__ import annotations
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field, RootModel, confloat, conint


class AgentType(Enum):
    document_analyzer = "document_analyzer"
    rag_validator = "rag_validator"
    report_generator = "report_generator"
    workflow_orchestrator = "workflow_orchestrator"
    fda_question_extractor = "fda_question_extractor"
    fda_answer_validator = "fda_answer_validator"
    fda_batch_orchestrator = "fda_batch_orchestrator"


class DocumentAnalyzerConfig(BaseModel):
    database: Optional[str] = Field(None, description="RAG database name to query documents from")
    retrieval_strategy: Optional[str] = Field("basic_search", description="Retrieval strategy name")
    max_context_length: Optional[int] = Field(
        50000, description="Maximum context length for LLM processing"
    )
    extraction_schema: Optional[dict[str, Any]] = Field(
        None, description="Pydantic schema for structured extraction (optional)"
    )


class RagValidatorConfig(BaseModel):
    database: Optional[str] = Field(None, description="RAG database name to validate against")
    retrieval_strategy: Optional[str] = Field("basic_search", description="Retrieval strategy name")
    top_k: Optional[int] = Field(5, description="Number of results to retrieve for validation")
    confidence_threshold: Optional[confloat(ge=0.0, le=1.0)] = Field(
        0.7, description="Minimum confidence score for validation"
    )


class Format(Enum):
    json = "json"
    markdown = "markdown"
    html = "html"
    pdf = "pdf"


class ReportGeneratorConfig(BaseModel):
    format: Optional[Format] = Field("json", description="Output format for reports")
    include_statistics: Optional[bool] = Field(True, description="Include statistics in reports")
    group_by: Optional[list[str]] = Field([], description="Fields to group report data by")


class WorkflowStep(BaseModel):
    agent: str = Field(..., description="Agent name to execute")
    input_field: str = Field(..., description="Input field name from previous step")
    output_field: str = Field(..., description="Output field name for this step")


class WorkflowOrchestratorConfig(BaseModel):
    batch_size: Optional[int] = Field(10, description="Number of items to process in each batch")
    parallel_workers: Optional[int] = Field(
        2, description="Number of parallel workers for batch processing"
    )
    workflow: Optional[list[WorkflowStep]] = Field(
        [], description="Sequence of agent steps to execute"
    )


class FdaQuestionExtractorConfig(BaseModel):
    database: Optional[str] = Field(None, description="RAG database with full FDA documents")
    min_confidence: Optional[confloat(ge=0.0, le=1.0)] = Field(
        0.7, description="Minimum confidence threshold for extracted questions"
    )
    extract_informal: Optional[bool] = Field(
        True, description="Whether to extract administrative/informal questions"
    )


class FdaAnswerValidatorConfig(BaseModel):
    database: Optional[str] = Field(None, description="RAG database with response documents")
    retrieval_strategy: Optional[str] = Field(
        "semantic_search", description="Retrieval strategy name"
    )
    top_k: Optional[int] = Field(10, description="Number of chunks to retrieve")
    confidence_threshold: Optional[confloat(ge=0.0, le=1.0)] = Field(
        0.75, description="Minimum confidence for answered status"
    )
    max_recursion_depth: Optional[conint(ge=0, le=5)] = Field(
        2, description="Maximum recursive verification attempts"
    )


class FdaBatchOrchestratorConfig(BaseModel):
    batch_size: Optional[int] = Field(10, description="Documents per batch")
    output_path: Optional[str] = Field(
        "/tmp/fda_batch", description="Where to save progress and reports"
    )
    resume_on_failure: Optional[bool] = Field(True, description="Continue from last checkpoint")
    extractor_config: Optional[FdaQuestionExtractorConfig] = None
    validator_config: Optional[FdaAnswerValidatorConfig] = None


class ModelItem(BaseModel):
    name: str = Field(..., description="Unique agent identifier")
    type: AgentType
    model: Optional[str] = Field(
        None, description="Model name to use (references runtime.models.name)"
    )
    description: Optional[str] = Field(None, description="Human-readable description of the agent")
    system_prompt: Optional[str] = Field(None, description="Custom system prompt for the agent")
    config: Optional[dict[str, Any]] = Field(None, description="Agent-specific configuration")


class Model(RootModel[list[ModelItem]]):
    root: list[ModelItem] = Field(..., description="List of agent configurations")
