# generated by datamodel-codegen:
#   filename:  schema.yaml
#   timestamp: 2025-10-08T21:53:59+00:00

from __future__ import annotations
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field, RootModel, confloat


class AgentType(Enum):
    document_analyzer = "document_analyzer"
    rag_validator = "rag_validator"
    report_generator = "report_generator"
    workflow_orchestrator = "workflow_orchestrator"


class DocumentAnalyzerConfig(BaseModel):
    database: Optional[str] = Field(None, description="RAG database name to query documents from")
    retrieval_strategy: Optional[str] = Field("basic_search", description="Retrieval strategy name")
    max_context_length: Optional[int] = Field(
        50000, description="Maximum context length for LLM processing"
    )
    extraction_schema: Optional[dict[str, Any]] = Field(
        None, description="Pydantic schema for structured extraction (optional)"
    )


class RagValidatorConfig(BaseModel):
    database: Optional[str] = Field(None, description="RAG database name to validate against")
    retrieval_strategy: Optional[str] = Field("basic_search", description="Retrieval strategy name")
    top_k: Optional[int] = Field(5, description="Number of results to retrieve for validation")
    confidence_threshold: Optional[confloat(ge=0.0, le=1.0)] = Field(
        0.7, description="Minimum confidence score for validation"
    )


class Format(Enum):
    json = "json"
    markdown = "markdown"
    html = "html"
    pdf = "pdf"


class ReportGeneratorConfig(BaseModel):
    format: Optional[Format] = Field("json", description="Output format for reports")
    include_statistics: Optional[bool] = Field(True, description="Include statistics in reports")
    group_by: Optional[list[str]] = Field([], description="Fields to group report data by")


class WorkflowStep(BaseModel):
    agent: str = Field(..., description="Agent name to execute")
    input_field: str = Field(..., description="Input field name from previous step")
    output_field: str = Field(..., description="Output field name for this step")


class WorkflowOrchestratorConfig(BaseModel):
    batch_size: Optional[int] = Field(10, description="Number of items to process in each batch")
    parallel_workers: Optional[int] = Field(
        2, description="Number of parallel workers for batch processing"
    )
    workflow: Optional[list[WorkflowStep]] = Field(
        [], description="Sequence of agent steps to execute"
    )


class ModelItem(BaseModel):
    name: str = Field(..., description="Unique agent identifier")
    type: AgentType
    model: Optional[str] = Field(
        None, description="Model name to use (references runtime.models.name)"
    )
    description: Optional[str] = Field(None, description="Human-readable description of the agent")
    system_prompt: Optional[str] = Field(None, description="Custom system prompt for the agent")
    config: Optional[dict[str, Any]] = Field(None, description="Agent-specific configuration")


class Model(RootModel[list[ModelItem]]):
    root: list[ModelItem] = Field(..., description="List of agent configurations")
